apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - env: dev
            namespace: dev
          - env: staging
            namespace: staging
          - env: prod
            namespace: prod
      - list:
          elements:
          - service: microservice-a
          - service: microservice-b
          - service: microservice-c
          - service: microservice-d
          - service: microservice-e
  template:
    metadata:
      name: '{{service}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/BBrucelee2002/gitops-argocd-model.git
        targetRevision: main
        path: environments/{{env}}/{{service}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          syncOptions:
          - CreateNamespace=true  # 👈 Argo CD will auto-create the "dev" namespace
