apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - microservice-a
  - microservice-b
  - microservice-c
  - microservice-d
  - microservice-e
  - gateway.yaml

patches:
  - target:
      kind: Gateway
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev-gateway
  - target:
      kind: VirtualService
      name: .*
    patch: |-
      - op: replace
        path: /spec/hosts/0
        value: dev.example.com
      - op: replace
        path: /spec/gateways/0
        value: dev-gateway

generatorOptions:
  disableNameSuffixHash: true