apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - microservice-a
  - microservice-b
  - microservice-c
  - microservice-d
  - microservice-e
  - gateway.yaml

vars:
  - name: ISTIO_GATEWAY
    literal: dev-gateway
  - name: VIRTUAL_SERVICE_HOST
    literal: dev.example.com

generatorOptions:
  disableNameSuffixHash: true