apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - microservice-a
  - microservice-b
  - microservice-c
  - microservice-d
  - microservice-e
  - gateway.yaml

configMapGenerator:
  - name: global-config
    literals:
      - istioGateway=dev-gateway
      - virtualServiceHost=dev.example.com

generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: ISTIO_GATEWAY
    objref:
      kind: ConfigMap
      name: global-config
      apiVersion: v1
    fieldref:
      fieldpath: data.istioGateway
  - name: VIRTUAL_SERVICE_HOST
    objref:
      kind: ConfigMap
      name: global-config
      apiVersion: v1
    fieldref:
      fieldpath: data.virtualServiceHost
