apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-env-app-of-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/BBrucelee2002/gitops-argocd-appofapps-appset.git
        revision: HEAD
        directories:
          - path: environments/*
  template:
    metadata:
      name: '{{path.basename}}-'
    spec:
      project: default
      source:
        repoURL: https://github.com/BBrucelee2002/gitops-argocd-appofapps-appset.git
        targetRevision: HEAD
        path: environments/{{path.basename}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
