apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-microservices
  namespace: argocd  # Argo CD must be installed in this namespace
spec:
  project: default
  source:
    repoURL: https://github.com/BBrucelee2002/gitops-argocd-model.git  # your Git repo
    targetRevision: main
    path: environments/dev   # path to the dev overlay
  destination:
    server: https://kubernetes.default.svc
    namespace: dev           # this namespace will be auto-created
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
